GET http://localhost:3001/api/blogs
###
GET http://localhost:3001/api/blogs/662b958ce24c3173e909e6b3
###
DELETE http://localhost:3001/api/blogs
###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{ 
    "title": "da vinci code",
    "author": "dan brown",
    "url": "http://gigidosoidk",
    "likes": 1111111111
}